name: 'Go Build'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Build
      id: build
      run: go build main.go
      shell: bash

    - name: Test
      run: go test
      shell: bash