on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  go_test_job:
    runs-on: ubuntu-latest
    name: Go Build & Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - id: gotest
        uses: ./.github/actions/gotest
